[package]
name = "psrs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

# cargo install:
# cargo-equip = "0.20.1" 
# cargo-udeps = "0.1.59"
